# Generated by Django 6.0 on 2025-12-15 02:49

import apps.core.utils
import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='report',
            name='task',
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات گزارش')),
                ('status', models.CharField(blank=True, choices=[('2', 'درحال اجرا'), ('1', 'موفق'), ('3', 'ناموفق')], default='2', max_length=50, null=True, verbose_name='وضعیت گزارش')),
                ('file_upload_reports', models.FileField(blank=True, null=True, upload_to=apps.core.utils.FileUpload.upload_to, verbose_name='فایل گزارش')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت گزارش')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کارمند ثبت کننده')),
            ],
            options={
                'verbose_name': 'گزارش',
                'verbose_name_plural': 'گزارشات',
                'ordering': ['-created_at'],
            },
        ),
    ]
