# Generated by Django 6.0 on 2025-12-15 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_report_employee_remove_report_task_reports'),
        ('tasks', '0002_tasks_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='tasks.tasks', verbose_name='وظیفه'),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
