# Generated by Django 6.0 on 2025-12-15 02:31

import apps.core.utils
import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('companies', '0002_alter_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('national_code', models.CharField(max_length=11, unique=True, verbose_name='کد ملی')),
                ('email', models.EmailField(blank=True, max_length=200, verbose_name='ایمیل')),
                ('mobile_number', models.CharField(max_length=11, unique=True, verbose_name='شماره موبایل')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='نام')),
                ('family', models.CharField(blank=True, max_length=50, verbose_name='نام خانوادگی')),
                ('father_name', models.CharField(blank=True, max_length=50, verbose_name='نام پدر')),
                ('birth_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('certificate', models.IntegerField(blank=True, choices=[(1, 'دیپلم'), (2, 'کارشناسی'), (3, 'کارشناسی ارشد'), (4, 'دکتری')], null=True, verbose_name='مدرک تحصیلی')),
                ('marital_status', models.BooleanField(blank=True, choices=[(True, 'بله'), (False, 'خیر')], default='True', max_length=50, null=True, verbose_name='وظعیت تاهل')),
                ('gender', models.BooleanField(blank=True, choices=[(True, 'مرد'), (False, 'زن')], default='True', max_length=50, null=True, verbose_name='جنسیت')),
                ('register_date', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('employee_address', models.TextField(blank=True, null=True, verbose_name='ادرس محل سکونت کارمند')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعال')),
                ('is_admin', models.BooleanField(default=False, verbose_name='وضعیت هماهنگ کننده')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.core.utils.FileUpload.upload_to, verbose_name='اپلود عکس')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company', verbose_name='شرکت')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارمندان',
            },
        ),
    ]
