# Generated by Django 6.0 on 2025-12-15 02:49

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.utils.FileUpload.upload_to, verbose_name='اپلود عکس'),
        ),
    ]
