# Generated by Django 6.0 on 2025-12-14 17:41

import django.db.models.deletion
import django_jalali.db.models
import utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان وظیفه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات وظیفه')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعال گزارش')),
                ('start_date', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ پایان')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت گزارش')),
                ('employees', models.ManyToManyField(blank=True, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='کارمندان مرتبط')),
            ],
            options={
                'verbose_name': 'وظیفه',
                'verbose_name_plural': 'وظایف',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات گزارش')),
                ('status', models.CharField(blank=True, choices=[('2', 'درحال اجرا'), ('1', 'موفق'), ('3', 'ناموفق')], default='2', max_length=50, null=True, verbose_name='وضعیت گزارش')),
                ('file_upload_reports', models.FileField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='فایل گزارش')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت گزارش')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کارمند ثبت کننده')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='tasks_and_reports.tasks', verbose_name='وظیفه')),
            ],
            options={
                'verbose_name': 'گزارش',
                'verbose_name_plural': 'گزارشات',
                'ordering': ['-created_at'],
            },
        ),
    ]
