# Generated by Django 6.0 on 2025-12-14 17:41

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم شرکت')),
                ('address_company', models.CharField(max_length=200, verbose_name='ادرس شرکت')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس شرکت')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='عکس لگو شرکت')),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': 'شرکت ها',
            },
        ),
    ]
