# Generated by Django 6.0 on 2025-12-15 02:31

import apps.core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.utils.FileUpload.upload_to, verbose_name='عکس لگو شرکت'),
        ),
    ]
