# Generated by Django 6.0 on 2025-12-15 02:49

import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_report_employee_remove_report_task_reports'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان وظیفه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات وظیفه')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعال گزارش')),
                ('start_date', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ پایان')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت گزارش')),
                ('employees', models.ManyToManyField(blank=True, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='کارمندان مرتبط')),
            ],
            options={
                'verbose_name': 'وظیفه',
                'verbose_name_plural': 'وظایف',
            },
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
